services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-gateway
    environment:
      BULLEX_SERVICE_URL: "http://bullex-service:8000"
      CORS_ORIGINS: "http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174"
      PANEL_API_KEY: "40402400kkj"
      SUPABASE_URL: "https://ynqevdkyrnxsgnzmlvix.supabase.co"
      SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlucWV2ZGt5cm54c2duem1sdml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExNTc2MDUsImV4cCI6MjA5NjczMzYwNX0.JfUfQBizVp1YJov2hanUDteay9NW4BWpblIBBt7HiYk"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - bullex-service

  bullex-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bullex-service
    environment:
      BULLEX_MAX_CONCURRENT_API_CALLS: "1"
    expose:
      - "8000"
    restart: unless-stopped
